import json
import base64
from PIL import Image, ImageDraw, ImageFont, ImageEnhance
import io

def image_to_base64_with_prefix(image_path):

    with Image.open(image_path) as image:
        buffered = io.BytesIO()
        image_format = image.format
        image.save(buffered, format=image_format)
        img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')

        # Adding the appropriate prefix based on the image format
        prefix = f"data:image/{image_format.lower()};base64,"
        return prefix + img_str








def create_custom_json(cluster_id, header, body_text, banner_image, logo_image, user_uploaded_image=None,template="newsletter"):


    asset_json = f"asset_{cluster_id}.json"

    if user_uploaded_image==None and template=="newsletter":
        json_structure = base_json = {'adjustments': {'crop': {'height': None,
                                'ratio': 'original',
                                'ratioTitleKey': 'original',
                                'width': None,
                                'x': 0,
                                'y': 0},
                        'isFlippedX': False,
                        'isFlippedY': False,
                        'rotation': 0},
        'annotations': {'Image-919838100372': {'disableUpload': False,
                                                'gallery': [],
                                                'height': 612.1860701576004,
                                                'id': 'Image-919838100372',
                                                'image': image_to_base64_with_prefix(banner_image),
                                                'name': 'Image',
                                                'opacity': 1,
                                                'rotation': 0,
                                                'scaleX': 0.4524360166420758,
                                                'scaleY': 0.4524360166420761,
                                                'shadowBlur': 0,
                                                'shadowColor': '#000000',
                                                'shadowOffsetX': 0,
                                                'shadowOffsetY': 0,
                                                'shadowOpacity': 1,
                                                'stroke': '#000000',
                                                'strokeWidth': 0,
                                                'width': 1071.3256227758006,
                                                'x': 360.0141928555345,
                                                'y': 84.77037822822545},
                        'Image-994896111078': {'disableUpload': False,
                                                'gallery': [],
                                                'height': 174,
                                                'id': 'Image-994896111078',
                                                'image': image_to_base64_with_prefix(logo_image),
                                                'name': 'Image',
                                                'opacity': 1,
                                                'rotation': 0,
                                                'scaleX': 0.35126508960058034,
                                                'scaleY': 0.3512650896005807,
                                                'shadowBlur': 0,
                                                'shadowColor': '#000000',
                                                'shadowOffsetX': 0,
                                                'shadowOffsetY': 0,
                                                'shadowOpacity': 1,
                                                'stroke': '#000000',
                                                'strokeWidth': 0,
                                                'width': 201,
                                                'x': 548.511577764665,
                                                'y': 631.6167187720308},
                        'Line-1208019748804': {'fill': '#ff0000',
                                                'id': 'Line-1208019748804',
                                                'lineCap': 'butt',
                                                'name': 'Line',
                                                'opacity': 1,
                                                'points': [0, 0, 898.4436963380566, 0],
                                                'rotation': 0,
                                                'scaleX': 1,
                                                'scaleY': 1,
                                                'shadowBlur': 0,
                                                'shadowColor': '#000000',
                                                'shadowOffsetX': 0,
                                                'shadowOffsetY': 0,
                                                'shadowOpacity': 1,
                                                'stroke': '#000000',
                                                'strokeWidth': 1,
                                                'x': 148.3292130844942,
                                                'y': -33.84548171136515},
                        'Line-1491673212846': {'fill': '#ff0000',
                                                'id': 'Line-1491673212846',
                                                'lineCap': 'butt',
                                                'name': 'Line',
                                                'opacity': 1,
                                                'points': [0,
                                                        0,
                                                        983.0574006164694,
                                                        1.5384309868802575],
                                                'shadowBlur': 0,
                                                'shadowColor': '#000000',
                                                'shadowOffsetX': 0,
                                                'shadowOffsetY': 0,
                                                'shadowOpacity': 1,
                                                'stroke': '#000000',
                                                'strokeWidth': 1,
                                                'x': 106.7915764387277,
                                                'y': 709.0784466533731},
                        'Line-250060049400': {'fill': '#ff0000',
                                            'id': 'Line-250060049400',
                                            'lineCap': 'butt',
                                            'name': 'Line',
                                            'opacity': 1,
                                            'points': [0,
                                                        0,
                                                        6.15372394752103,
                                                        713.6937396140136],
                                            'shadowBlur': 0,
                                            'shadowColor': '#000000',
                                            'shadowOffsetX': 0,
                                            'shadowOffsetY': 0,
                                            'shadowOpacity': 1,
                                            'stroke': '#000000',
                                            'strokeWidth': 1,
                                            'x': 1082.1568221207958,
                                            'y': 0},
                        'Line-317431922676': {'fill': '#ff0000',
                                            'id': 'Line-317431922676',
                                            'lineCap': 'butt',
                                            'name': 'Line',
                                            'opacity': 1,
                                            'points': [0, 0, 967.673090747667, 0],
                                            'shadowBlur': 0,
                                            'shadowColor': '#000000',
                                            'shadowOffsetX': 0,
                                            'shadowOffsetY': 0,
                                            'shadowOpacity': 1,
                                            'stroke': '#000000',
                                            'strokeWidth': 1,
                                            'x': 114.48373137312899,
                                            'y': 0},
                        'Line-406492438963': {'fill': '#ff0000',
                                            'id': 'Line-406492438963',
                                            'lineCap': 'butt',
                                            'name': 'Line',
                                            'opacity': 1,
                                            'points': [0, 0, 989.2111245639903, 0],
                                            'shadowBlur': 0,
                                            'shadowColor': '#000000',
                                            'shadowOffsetX': 0,
                                            'shadowOffsetY': 0,
                                            'shadowOpacity': 1,
                                            'stroke': '#000000',
                                            'strokeWidth': 1,
                                            'x': 94.48412854368598,
                                            'y': -38.46077467200587},
                        'Line-576187491989': {'fill': '#ff0000',
                                            'id': 'Line-576187491989',
                                            'lineCap': 'butt',
                                            'name': 'Line',
                                            'opacity': 1,
                                            'points': [0,
                                                        0,
                                                        -1.5384309868802575,
                                                        679.9864962010632],
                                            'rotation': 0,
                                            'scaleX': 1.0479224287532496,
                                            'scaleY': 1.0479224287532398,
                                            'shadowBlur': 0,
                                            'shadowColor': '#000000',
                                            'shadowOffsetX': 0,
                                            'shadowOffsetY': 0,
                                            'shadowOpacity': 1,
                                            'stroke': '#000000',
                                            'strokeWidth': 1,
                                            'x': 111.50455596310546,
                                            'y': -1.670527654849841},
                        'Text-1319700547052': {'align': 'center',
                                                'fill': 'rgb(0, 0, 0)',
                                                'fontFamily': 'Arial',
                                                'fontSize': 29,
                                                'fontStyle': 'normal',
                                                'height': 82.24615238675827,
                                                'id': 'Text-1319700547052',
                                                'letterSpacing': 0,
                                                'lineHeight': 1,
                                                'name': 'Text',
                                                'opacity': 1,
                                                'rotation': 0,
                                                'scaleX': 1,
                                                'scaleY': 1,
                                                'shadowBlur': 0,
                                                'shadowColor': '#000000',
                                                'shadowOffsetX': 0,
                                                'shadowOffsetY': 0,
                                                'shadowOpacity': 1,
                                                'stroke': '#000000',
                                                'strokeWidth': 0,
                                                'text': header,
                                                'width': 505.89142788836403,
                                                'x': 357.0173764547955,
                                                'y': 14.130709104899044},
                        'Text-1580461729122': {'align': 'left',
                                                'fill': 'rgb(0, 0, 0)',
                                                'fontFamily': 'Arial',
                                                'fontSize': 14,
                                                'fontStyle': 'normal',
                                                'height': 218.99565098240146,
                                                'id': 'Text-1580461729122',
                                                'letterSpacing': 0,
                                                'lineHeight': 1,
                                                'name': 'Text',
                                                'opacity': 1,
                                                'shadowBlur': 0,
                                                'shadowColor': '#000000',
                                                'shadowOffsetX': 0,
                                                'shadowOffsetY': 0,
                                                'shadowOpacity': 1,
                                                'stroke': '#000000',
                                                'strokeWidth': 0,
                                                'text': body_text,
                                                'width': 724.9856025673106,
                                                'x': 244.01962046844483,
                                                'y': 400.12304371314997}},
        'filter': None,
        'finetunes': [],
        'finetunesProps': {},
        'imgSrc': 'https://filerobot-image-editor-nextjs.vercel.app/blank-white-background.jpg',
        'resize': {},
        'shownImageDimensions': {'height': 721.24765625,
                                'scaledBy': 1,
                                'width': 1232.0244661921708}}
        try:
            with open(asset_json, 'w') as json_file:
                json.dump(json_structure, json_file, indent=4)
            print(f"File successfully saved as {asset_json}")
            return asset_json
        except Exception as e:
            return asset_json
        
    if user_uploaded_image!=None and template=="newsletter":
        json_structure = base_json = {'adjustments': {'crop': {'height': None,
                                        'ratio': 'original',
                                        'ratioTitleKey': 'original',
                                        'width': None,
                                        'x': 0,
                                        'y': 0},
                                'isFlippedX': False,
                                'isFlippedY': False,
                                'rotation': 0},
                'annotations': {'Image-112163985785': {'disableUpload': False,
                                                        'gallery': [],
                                                        'height': 600,
                                                        'id': 'Image-112163985785',
                                                        'image': image_to_base64_with_prefix(banner_image),
                                                        'name': 'Image',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 0.12324379677930683,
                                                        'scaleY': 0.12324379677930686,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'width': 600,
                                                        'x': 549.9467085683763,
                                                        'y': 594.5523460389394},
                                'Image-1335752175416': {'disableUpload': False,
                                                        'gallery': [],
                                                        'height': 537.6071410118129,
                                                        'id': 'Image-1335752175416',
                                                        'image': image_to_base64_with_prefix(user_uploaded_image),
                                                        'name': 'Image',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 0.33070375466917235,
                                                        'scaleY': 0.33070375466917223,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'width': 1071.3256227758009,
                                                        'x': 419.34268966724363,
                                                        'y': 141.81926469270127},
                                'Image-40796186113': {'disableUpload': False,
                                                    'gallery': [],
                                                    'height': 612.1860701576004,
                                                    'id': 'Image-40796186113',
                                                    'image': image_to_base64_with_prefix(logo_image),
                                                    'name': 'Image',
                                                    'opacity': 1,
                                                    'rotation': 0,
                                                    'scaleX': 0.5963853764024052,
                                                    'scaleY': 0.4620189102878911,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 1071.3256227758006,
                                                    'x': 277.5856414118966,
                                                    'y': 84.49775981416809},
                                'Line-1208019748804': {'fill': '#ff0000',
                                                        'id': 'Line-1208019748804',
                                                        'lineCap': 'butt',
                                                        'name': 'Line',
                                                        'opacity': 1,
                                                        'points': [0, 0, 898.4436963380566, 0],
                                                        'rotation': 0,
                                                        'scaleX': 1,
                                                        'scaleY': 1,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 1,
                                                        'x': 148.3292130844942,
                                                        'y': -33.84548171136515},
                                'Line-1491673212846': {'fill': '#ff0000',
                                                        'id': 'Line-1491673212846',
                                                        'lineCap': 'butt',
                                                        'name': 'Line',
                                                        'opacity': 1,
                                                        'points': [0,
                                                                0,
                                                                983.0574006164694,
                                                                1.5384309868802575],
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 1,
                                                        'x': 106.7915764387277,
                                                        'y': 709.0784466533731},
                                'Line-250060049400': {'fill': '#ff0000',
                                                    'id': 'Line-250060049400',
                                                    'lineCap': 'butt',
                                                    'name': 'Line',
                                                    'opacity': 1,
                                                    'points': [0,
                                                                0,
                                                                6.15372394752103,
                                                                713.6937396140136],
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 1,
                                                    'x': 1082.1568221207958,
                                                    'y': 0},
                                'Line-317431922676': {'fill': '#ff0000',
                                                    'id': 'Line-317431922676',
                                                    'lineCap': 'butt',
                                                    'name': 'Line',
                                                    'opacity': 1,
                                                    'points': [0, 0, 967.673090747667, 0],
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 1,
                                                    'x': 114.48373137312899,
                                                    'y': 0},
                                'Line-406492438963': {'fill': '#ff0000',
                                                    'id': 'Line-406492438963',
                                                    'lineCap': 'butt',
                                                    'name': 'Line',
                                                    'opacity': 1,
                                                    'points': [0, 0, 989.2111245639903, 0],
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 1,
                                                    'x': 94.48412854368598,
                                                    'y': -38.46077467200587},
                                'Line-576187491989': {'fill': '#ff0000',
                                                    'id': 'Line-576187491989',
                                                    'lineCap': 'butt',
                                                    'name': 'Line',
                                                    'opacity': 1,
                                                    'points': [0,
                                                                0,
                                                                -1.5384309868802575,
                                                                679.9864962010632],
                                                    'rotation': 0,
                                                    'scaleX': 1.0479224287532496,
                                                    'scaleY': 1.0479224287532398,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 1,
                                                    'x': 111.50455596310546,
                                                    'y': -1.670527654849841},
                                'Text-1319700547052': {'align': 'center',
                                                        'fill': 'rgb(0, 0, 0)',
                                                        'fontFamily': 'Arial',
                                                        'fontSize': 29,
                                                        'fontStyle': 'normal',
                                                        'height': 82.24615238675827,
                                                        'id': 'Text-1319700547052',
                                                        'letterSpacing': 0,
                                                        'lineHeight': 1,
                                                        'name': 'Text',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 1,
                                                        'scaleY': 1,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'text': header,
                                                        'width': 505.89142788836403,
                                                        'x': 335.01781334240815,
                                                        'y': 14.130709104899044},
                                'Text-328755962737': {'align': 'left',
                                                    'fill': 'rgb(0, 0, 0)',
                                                    'fontFamily': 'Arial',
                                                    'fontSize': 14,
                                                    'fontStyle': 'normal',
                                                    'height': 213.35758576211043,
                                                    'id': 'Text-328755962737',
                                                    'letterSpacing': 0,
                                                    'lineHeight': 1,
                                                    'name': 'Text',
                                                    'opacity': 1,
                                                    'rotation': 0,
                                                    'scaleX': 1,
                                                    'scaleY': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'text': body_text,
                                                    'width': 652.2856856275972,
                                                    'x': 275.0190048540804,
                                                    'y': 400.1230437131514}},
                'filter': None,
                'finetunes': [],
                'finetunesProps': {},
                'imgSrc': 'https://filerobot-image-editor-nextjs.vercel.app/blank-white-background.jpg',
                'resize': {},
                'shownImageDimensions': {'height': 721.24765625,
                                        'scaledBy': 1,
                                        'width': 1232.0244661921708}}
        try:
            with open(asset_json, 'w') as json_file:
                json.dump(json_structure, json_file, indent=4)
            print(f"File successfully saved as {asset_json}")
            return asset_json
        except Exception as e:
            return asset_json
        

    if user_uploaded_image!=None and template=="social_media_ads":
        json_structure = base_json = {'adjustments': {'crop': {'height': None,
                          'ratio': 'original',
                          'ratioTitleKey': 'original',
                          'width': None,
                          'x': 0,
                          'y': 0},
                                'isFlippedX': False,
                                'isFlippedY': False,
                                'rotation': 0},
                'annotations': {'Image-1311723309978': {'disableUpload': False,
                                                        'gallery': [],
                                                        'height': 188,
                                                        'id': 'Image-1311723309978',
                                                        'image': image_to_base64_with_prefix(banner_image),
                                                        'name': 'Image',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 0.2502087097203574,
                                                        'scaleY': 0.2502087097203573,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'width': 530,
                                                        'x': 547.0083408246256,
                                                        'y': 55.628018274375904},
                                'Image-749150927136': {'disableUpload': False,
                                                        'gallery': [],
                                                        'height': 627.171875,
                                                        'id': 'Image-749150927136',
                                                        'image': image_to_base64_with_prefix(logo_image),
                                                        'name': 'Image',
                                                        'opacity': 0.49,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'width': 627.171875,
                                                        'x': 302.4262955960854,
                                                        'y': 47.03789062499999},
                                'Rect-134396980071': {'cornerRadius': 0,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 4.99990070736078,
                                                    'id': 'Rect-134396980071',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 5.999880848832845,
                                                    'x': 449.015549470236,
                                                    'y': 276.1255061706031},
                                'Rect-423925053582': {'cornerRadius': 0,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 130.99739853285206,
                                                    'id': 'Rect-423925053582',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 280.9944197536747,
                                                    'x': 328.01795235210557,
                                                    'y': 434.12236852320314},
                                'Rect-654076485894': {'cornerRadius': 15,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 157.99686235260003,
                                                    'id': 'Rect-654076485894',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'rotation': 0,
                                                    'scaleX': 0.9928324885866727,
                                                    'scaleY': 0.7396875753713859,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 1,
                                                    'width': 403.99197715474963,
                                                    'x': 410.99634111444533,
                                                    'y': 247.4917126760899},
                                'Rect-72302039105': {'cornerRadius': 0,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 1.9999602829443006,
                                                    'id': 'Rect-72302039105',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 1.9999602829443575,
                                                    'x': 525.0140402221195,
                                                    'y': 286.1253075853246},
                                'Text-1070281860826': {'align': 'left',
                                                        'fill': 'rgb(0, 0, 0)',
                                                        'fontFamily': 'Arial',
                                                        'fontSize': 14,
                                                        'fontStyle': 'normal',
                                                        'height': 109.99781556193676,
                                                        'id': 'Text-1070281860826',
                                                        'letterSpacing': 0,
                                                        'lineHeight': 1,
                                                        'name': 'Text',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 1,
                                                        'scaleY': 1,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'text': body_text,
                                                        'width': 382.9923941838374,
                                                        'x': 419.70949816521244,
                                                        'y': 269.677574144491},
                                'Text-403673583106': {'align': 'left',
                                                    'fill': 'rgb(0, 0, 0)',
                                                    'fontFamily': 'Sans-serif',
                                                    'fontSize': 25,
                                                    'fontStyle': 'bold',
                                                    'height': 99.9980141472152,
                                                    'id': 'Text-403673583106',
                                                    'letterSpacing': 0,
                                                    'lineHeight': 6,
                                                    'name': 'Text',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'text': header,
                                                    'width': 445.99114309658,
                                                    'x': 408.0664252539318,
                                                    'y': 140.02307760387768}},
                'filter': None,
                'finetunes': [],
                'finetunesProps': {},
                'imgSrc': 'https://filerobot-image-editor-nextjs.vercel.app/blank-white-background.jpg',
                'resize': {},
                'shownImageDimensions': {'height': 721.24765625,
                                        'scaledBy': 1,
                                        'width': 1232.0244661921708}}
        try:
            with open(asset_json, 'w') as json_file:
                json.dump(json_structure, json_file, indent=4)
            print(f"File successfully saved as {asset_json}")
            return asset_json
        except Exception as e:
            return asset_json

    if user_uploaded_image==None and template=="social_media_ads":
        json_structure = base_json = {'adjustments': {'crop': {'height': None,
                          'ratio': 'original',
                          'ratioTitleKey': 'original',
                          'width': None,
                          'x': 0,
                          'y': 0},
                                'isFlippedX': False,
                                'isFlippedY': False,
                                'rotation': 0},
                'annotations': {'Image-1311723309978': {'disableUpload': False,
                                                        'gallery': [],
                                                        'height': 188,
                                                        'id': 'Image-1311723309978',
                                                        'image': image_to_base64_with_prefix(banner_image),
                                                        'name': 'Image',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 0.2502087097203574,
                                                        'scaleY': 0.2502087097203573,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'width': 530,
                                                        'x': 547.0083408246256,
                                                        'y': 55.628018274375904},
                                'Image-749150927136': {'disableUpload': False,
                                                        'gallery': [],
                                                        'height': 627.171875,
                                                        'id': 'Image-749150927136',
                                                        'image': image_to_base64_with_prefix(logo_image),
                                                        'name': 'Image',
                                                        'opacity': 0.49,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'width': 627.171875,
                                                        'x': 302.4262955960854,
                                                        'y': 47.03789062499999},
                                'Rect-134396980071': {'cornerRadius': 0,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 4.99990070736078,
                                                    'id': 'Rect-134396980071',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 5.999880848832845,
                                                    'x': 449.015549470236,
                                                    'y': 276.1255061706031},
                                'Rect-423925053582': {'cornerRadius': 0,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 130.99739853285206,
                                                    'id': 'Rect-423925053582',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 280.9944197536747,
                                                    'x': 328.01795235210557,
                                                    'y': 434.12236852320314},
                                'Rect-654076485894': {'cornerRadius': 15,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 157.99686235260003,
                                                    'id': 'Rect-654076485894',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'rotation': 0,
                                                    'scaleX': 0.9928324885866727,
                                                    'scaleY': 0.7396875753713859,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 1,
                                                    'width': 403.99197715474963,
                                                    'x': 410.99634111444533,
                                                    'y': 247.4917126760899},
                                'Rect-72302039105': {'cornerRadius': 0,
                                                    'fill': 'rgba(0,0,0,0)',
                                                    'height': 1.9999602829443006,
                                                    'id': 'Rect-72302039105',
                                                    'name': 'Rect',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'width': 1.9999602829443575,
                                                    'x': 525.0140402221195,
                                                    'y': 286.1253075853246},
                                'Text-1070281860826': {'align': 'left',
                                                        'fill': 'rgb(0, 0, 0)',
                                                        'fontFamily': 'Arial',
                                                        'fontSize': 14,
                                                        'fontStyle': 'normal',
                                                        'height': 109.99781556193676,
                                                        'id': 'Text-1070281860826',
                                                        'letterSpacing': 0,
                                                        'lineHeight': 1,
                                                        'name': 'Text',
                                                        'opacity': 1,
                                                        'rotation': 0,
                                                        'scaleX': 1,
                                                        'scaleY': 1,
                                                        'shadowBlur': 0,
                                                        'shadowColor': '#000000',
                                                        'shadowOffsetX': 0,
                                                        'shadowOffsetY': 0,
                                                        'shadowOpacity': 1,
                                                        'stroke': '#000000',
                                                        'strokeWidth': 0,
                                                        'text': body_text,
                                                        'width': 382.9923941838374,
                                                        'x': 419.70949816521244,
                                                        'y': 269.677574144491},
                                'Text-403673583106': {'align': 'left',
                                                    'fill': 'rgb(0, 0, 0)',
                                                    'fontFamily': 'Sans-serif',
                                                    'fontSize': 25,
                                                    'fontStyle': 'bold',
                                                    'height': 99.9980141472152,
                                                    'id': 'Text-403673583106',
                                                    'letterSpacing': 0,
                                                    'lineHeight': 6,
                                                    'name': 'Text',
                                                    'opacity': 1,
                                                    'shadowBlur': 0,
                                                    'shadowColor': '#000000',
                                                    'shadowOffsetX': 0,
                                                    'shadowOffsetY': 0,
                                                    'shadowOpacity': 1,
                                                    'stroke': '#000000',
                                                    'strokeWidth': 0,
                                                    'text': header,
                                                    'width': 445.99114309658,
                                                    'x': 408.0664252539318,
                                                    'y': 140.02307760387768}},
                'filter': None,
                'finetunes': [],
                'finetunesProps': {},
                'imgSrc': 'https://filerobot-image-editor-nextjs.vercel.app/blank-white-background.jpg',
                'resize': {},
                'shownImageDimensions': {'height': 721.24765625,
                                        'scaledBy': 1,
                                        'width': 1232.0244661921708}}
        try:
            with open(asset_json, 'w') as json_file:
                json.dump(json_structure, json_file, indent=4)
            print(f"File successfully saved as {asset_json}")
            return asset_json
        except Exception as e:
            return asset_json
